version: '2'

services:
    mysql:
        container_name: sym_mc_db
        image: mysql/mysql-server:5.7
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            TZ:  ${TIMEZONE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        container_name: sym_mc_php
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/logs
    nginx:
        container_name: sym_mc_nginx
        build: docker/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
