<?php

namespace AppBundle\Repository;

/**
 * BestandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestandRepository extends \Doctrine\ORM\EntityRepository
{
}
