<?php

namespace AppBundle\Repository;

/**
 * BestandstypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestandstypeRepository extends \Doctrine\ORM\EntityRepository
{
}
