<?php

namespace AppBundle\Repository;

/**
 * OndertitelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OndertitelRepository extends \Doctrine\ORM\EntityRepository
{
}
