<?php

namespace AppBundle\Repository;

/**
 * SchijfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchijfRepository extends \Doctrine\ORM\EntityRepository
{
}
